version: "3.0"

services:
  python38:
    build:
      context: ./
      dockerfile: "./docker/python/Dockerfile"
    container_name: "deep-learning-app_python38"
    working_dir: /var/www/project
    restart: always
    volumes:
      - ./src:/var/www/project/src
    expose:
      - "6030"
    env_file: ./.env

  nginx:
    image: nginx:1.21-alpine
    container_name: "deep-learning-app_nginx"
    # NginxのDockerfileをビルドする
    build:
      # ビルドコンテキストはカレントディレクトリ
      context: ./
      dockerfile: "./docker/nginx/Dockerfile"
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./docker/nginx/log:/var/log/nginx
    restart: always
    env_file: ./.env
    depends_on:
      - python38
    ports:
      - "6030:80"
    links:
      - python38